# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-25 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('symptomtracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideEffectGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('grading_patient_friendly', models.TextField()),
                ('intervention_patient_friendly', models.TextField()),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptomtracker.Symptom')),
            ],
            options={
                'verbose_name': 'side effect grade',
                'verbose_name_plural': 'side effect grades',
            },
        ),
    ]
