# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-25 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('symptomtracker', '0002_sideeffectgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'grade',
                'verbose_name_plural': 'grades',
            },
        ),
        migrations.CreateModel(
            name='SymptomGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('grading_patient_friendly', models.TextField()),
                ('intervention_patient_friendly', models.TextField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptomtracker.Grade')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptomtracker.Symptom')),
            ],
            options={
                'verbose_name': 'symptom grade description',
                'verbose_name_plural': 'symptom grade descriptions',
            },
        ),
        migrations.RemoveField(
            model_name='sideeffectgrade',
            name='symptom',
        ),
        migrations.DeleteModel(
            name='SideEffectGrade',
        ),
    ]
