# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-27 23:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('symptomtracker', '0003_auto_20180124_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSymptomGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptomtracker.Symptom')),
            ],
            options={
                'verbose_name': 'patient symptom grade',
                'verbose_name_plural': 'patient symptom grades',
            },
        ),
        migrations.RemoveField(
            model_name='symptomgrade',
            name='grading_patient_friendly',
        ),
        migrations.RemoveField(
            model_name='symptomgrade',
            name='intervention_patient_friendly',
        ),
        migrations.AddField(
            model_name='patientsymptomgrade',
            name='symptom_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptomtracker.SymptomGrade'),
        ),
    ]
