# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-30 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('symptomtracker', '0004_auto_20180127_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientsymptomgrade',
            options={'ordering': ('recorded_at',), 'verbose_name': 'patient symptom grade', 'verbose_name_plural': 'patient symptom grades'},
        ),
        migrations.AlterField(
            model_name='patientsymptomgrade',
            name='symptom_grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptomtracker.Grade'),
        ),
    ]
