# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-05 04:32
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('symptomtracker', '0005_auto_20180130_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptomtracker.Grade')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptomtracker.Symptom')),
            ],
            options={
                'verbose_name': 'intervention',
                'verbose_name_plural': 'interventions',
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('icon', models.CharField(max_length=30)),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptomtracker.Symptom')),
            ],
            options={
                'verbose_name': 'tip',
                'verbose_name_plural': 'tips',
            },
        ),
    ]
