# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-02 21:16
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.CharField(max_length=30)),
                ('reaction', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), size=None)),
            ],
            options={
                'verbose_name': 'allergy',
                'verbose_name_plural': 'allergies',
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.URLField()),
                ('gender', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=30)),
                ('medical_conditions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('medication_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('cancer_diagnosis', models.CharField(max_length=50)),
                ('chemotherapy', models.CharField(max_length=3)),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientprofile.Allergy')),
            ],
            options={
                'verbose_name': 'patient profile',
                'verbose_name_plural': 'patient profiles',
            },
        ),
    ]
