# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-02 21:36
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='allergy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patientprofile.Allergy'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='cancer_diagnosis',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='chemotherapy',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='medical_conditions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='medication_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='phone_number',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
