# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-03 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientprofile', '0003_auto_20180303_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientprofile.PatientProfile'),
        ),
    ]
